language: java
sudo: false

jdk:
 - oraclejdk7
 - openjdk7
 - oraclejdk8

cache:
  directories:
  - $HOME/.gradle
  - $HOME/.m2

install: ./gradlew assemble
script: ./gradlew check funcTest --stacktrace --info --continue
